# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kingname', models.CharField(max_length=20)),
                ('kinguser', models.CharField(max_length=20)),
                ('kingpato', models.IntegerField()),
                ('slaves', models.ManyToManyField(to='newbie.UsrContext')),
            ],
        ),
    ]
