# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='established',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='startT',
            field=models.CharField(default=b'00:00', max_length=20),
        ),
    ]
