# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0003_auto_20161204_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='kingphone',
            field=models.CharField(default=b'00000000000', max_length=20),
        ),
    ]
