# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbie', '0004_team_kingphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='destination',
            field=models.CharField(default=b'station1', max_length=20),
        ),
    ]
